// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Holder<T>;
    #[wasm_bindgen(constructor, catch)]
    pub fn new<T>(value: T) -> Result<Holder<T>, JsValue>;
    #[wasm_bindgen(method)]
    pub fn get<T>(this: &Holder<T>) -> T;
    #[wasm_bindgen(method, catch, js_name = "get")]
    pub fn try_get<T>(this: &Holder<T>) -> Result<T, JsValue>;
    #[wasm_bindgen(method)]
    pub fn set<T>(this: &Holder<T>, value: T);
    #[wasm_bindgen(method, catch, js_name = "set")]
    pub fn try_set<T>(this: &Holder<T>, value: T) -> Result<(), JsValue>;
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    pub fn identity<T>(value: T) -> T;
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "identity")]
    pub fn try_identity<T>(value: T) -> Result<T, JsValue>;
}
